/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClock_Setup(void);
void SetupSysTick_TIM(void);
void SetupLED_GPIO(void);
void ToggleLED_GPIO(void);
void Delay(uint32_t ticks);

int main(void)
{
	SystemClock_Setup();
	SetupLED_GPIO();

	while(1)
	{
		//Toggle and delay the LED for 1 second (
		ToggleLED_GPIO();
		Delay(720000);
	}
}

void SystemClock_Setup(void)
{
	// Enable HSE
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));

	// Set system clock to 72MHz - HSE is 8MHz x9
	RCC->CFGR |= RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL9;

	//Apply AHB/APB prescalers
	//PPRE2 - APB2 divided by 2
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
	//PPRE1 - APB1 divided by 4
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;

	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY));

	FLASH->ACR = FLASH_ACR_LATENCY_2; // Flash latency for high speed reading

	// Switch to PLL
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);

	// Turn off HSI
	RCC->CR &= ~RCC_CR_HSION;
}

void SetupSysTick_TIM(void)
{
	SysTick->CTRL = (1 << 2) |   // CLKSOURCE = 1 (AHB)
            		(1 << 1) |   // TICKINT   = 1 (enable interrupt)
					(1 << 0);    // ENABLE    = 1
}

void SetupLED_GPIO(void)
{
	//Enable Port C
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

	//Set PC13 as output with 10MHz max speed
	GPIOC->CRH |= GPIO_CRH_MODE13_0;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;
}

void ToggleLED_GPIO(void)
{
	GPIOC->ODR ^= GPIO_ODR_ODR13;
}

void Delay(uint32_t ticks)
{
	while(ticks--);
}
