/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

void SystemClock_Setup(void);
void SetupSysTick_TIM(void);
void SetupLED_GPIO(void);
void Setup_I2C(void);
void ToggleLED_GPIO(void);
void Delay(uint32_t ticks);

volatile uint32_t ms_ticks = 0;   // Global millisecond counter

int main(void)
{
	SystemClock_Setup();
	SetupSysTick_TIM();
	SetupLED_GPIO();

	while(1)
	{
		//Toggle and delay the LED for 1 second (
		ToggleLED_GPIO();
		Delay(5000);
		//Delay(720000);
	}
}

void SystemClock_Setup(void)
{
	// Enable HSE
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));

	// Set system clock to 72MHz - HSE is 8MHz x9
	RCC->CFGR |= RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL9;

	//Apply AHB/APB prescalers
	//PPRE2 - APB2 divided by 2 - 36MHz
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
	//PPRE1 - APB1 divided by 2 - 36MHz - MAX 36MHz!!
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;

	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY));

	FLASH->ACR = FLASH_ACR_LATENCY_2; // Flash latency for high speed reading

	// Switch to PLL
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);

	// Turn off HSI
	RCC->CR &= ~RCC_CR_HSION;
}

void SetupSysTick_TIM(void)
{
	SystemCoreClockUpdate();                    // Update SystemCoreClock variable

	// SysTick is a 24-bit down-counter
	SysTick->LOAD = (SystemCoreClock / 1000) - 1;   // Reload value for 1ms

	SysTick->VAL  = 0;                          // Clear current value

	// Configure Control Register:
	// Bit 2: CLKSOURCE = 1 (Processor clock = HCLK)
	// Bit 1: TICKINT   = 1 (Enable SysTick interrupt)
	// Bit 0: ENABLE    = 1
	SysTick->CTRL = (1 << 2) | (1 << 1) | (1 << 0);

}

void SetupLED_GPIO(void)
{
	//Enable Port C
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;

	//Set PC13 as output with 10MHz max speed
	GPIOC->CRH |= GPIO_CRH_MODE13_0;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;
}

void Setup_I2C(void)
{
	//Enable clock for Port B for I2C pins
	//Enable clock for AFIO
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_AFIOEN;
	//Enable clock for I2C1
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN;

	//Clear config bits
	GPIOB->CRL &= ~(GPIO_CRL_MODE6 | GPIO_CRL_MODE7);
	GPIOB->CRL &= ~(GPIO_CRL_CNF6 | GPIO_CRL_CNF7);
	//Set pin modes - alternate function output open-drain
	//PB6 - I2C1 SCL
	//PB7 - I2C1 SDA
	GPIOB->CRL |= GPIO_CRL_MODE6 | GPIO_CRL_MODE7;
	GPIOB->CRL |= GPIO_CRL_CNF6 | GPIO_CRL_CNF7;

	//Set alternate function for PB pins
	//No remapping needed
	AFIO->MAPR &= ~AFIO_MAPR_I2C1_REMAP;
}

void ToggleLED_GPIO(void)
{
	GPIOC->ODR ^= GPIO_ODR_ODR13;
}

uint32_t GetTick(void)
{
	return ms_ticks;
}

void Delay(uint32_t ticks)
{
	uint32_t init = GetTick();

	while((ms_ticks - init) < ticks); //may be unsafe, possible race condition
}

void SysTick_Handler(void)
{
	ms_ticks++;
}
